"""test_tree_validate_tombstone_exclusion.py —  regression test.

validate_tree's orphan-file walk counts every on-disk .md with no _tree.yaml
entry. Retired-tombstone files (moved-node stale twins tombstone-overwritten
per rb-3640 — S3 DeleteObject is IAM-denied, so the tombstone is the
retirement TERMINAL state, permanently on disk) must NOT count as orphans:
without the exclusion the orphan-warning count can never reach ~0 and the
tree_orphan_files ratchet baseline would be permanently polluted.

Covers:
  1. A retired-tombstone orphan → NO orphan warning.
  2. A true orphan (unreferenced, no tombstone marker) → exactly one warning
     (the check still catches real strays — new stranded twins surface).
  3. A referenced file whose body happens to contain the marker string is
     unaffected (referenced files never reach the content check).
"""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CORE_SCRIPTS = SCRIPT_DIR.parent
sys.path.insert(0, str(CORE_SCRIPTS))

import _paths  # noqa: E402
import tree  # noqa: E402

TOMBSTONE = """---
topic: "RETIRED legacy path — see canonical node"
status: retired-tombstone
retired: "2026-07-16"
retired_by: "g-115-2318 (bravo)"
---

# MOVED — do NOT edit this file
"""


def _tree_dict() -> dict:
    return {"nodes": {
        "root": {"file": None, "depth": 0, "parent": None,
                 "children": ["fiction"], "child_count": 1, "summary": "root"},
        "fiction": {"file": "world/knowledge/tree/fiction.md", "depth": 1,
                    "parent": "root", "children": ["alpha"],
                    "child_count": 1, "summary": "fiction"},
        "alpha": {"file": "world/knowledge/tree/fiction/alpha.md", "depth": 2,
                  "parent": "fiction", "children": [], "child_count": 0,
                  "summary": "alpha"},
    }}


def test_tombstone_not_counted_as_orphan(tmp_path, monkeypatch):
    tree_root = tmp_path / "knowledge" / "tree"
    (tree_root / "fiction").mkdir(parents=True)
    (tree_root / "fiction.md").write_text("# Fiction (L1)\n", encoding="utf-8")
    (tree_root / "fiction" / "alpha.md").write_text(
        "# Alpha\nBody mentions status: retired-tombstone as prose — "
        "referenced files never reach the orphan content check.\n",
        encoding="utf-8")
    # Tombstoned stale twin (unreferenced) — must be EXCLUDED.
    (tree_root / "fiction" / "alpha-legacy.md").write_text(
        TOMBSTONE, encoding="utf-8")
    # True orphan (unreferenced, no marker) — must still WARN.
    (tree_root / "fiction" / "stray.md").write_text(
        "# Stray\nA genuinely unreferenced node file.\n", encoding="utf-8")

    monkeypatch.setattr(_paths, "WORLD_DIR", tmp_path)
    monkeypatch.setattr(tree, "WORLD_DIR", tmp_path)

    warns = tree.validate_tree(_tree_dict())["warnings"]
    orphan = [w for w in warns if w.startswith("Orphan file")]
    assert len(orphan) == 1, "expected exactly the true stray: " + repr(orphan)
    assert "stray.md" in orphan[0]
    assert not any("alpha-legacy.md" in w for w in orphan), (
        "tombstoned twin must be excluded from orphan warnings")
