"""Tests for the structured dispatch split in _cadence_registry ().

WHAT CHANGED AND WHY IT NEEDS PINNING. `fire_dispatch` used to be a hand-written
prose string on every registry entry — the defect guard-5298 records: "a config
field whose VALUE is an instruction addressed to a reader is an unexecuted stage
wearing a config schema." It is now DERIVED by `_compose_dispatch()` from three
structured fields (`dispatch_skill` / `dispatch_args` / `dispatch_note`), so the
machine-readable form and the printed prose have exactly one writer and cannot
drift (communication-clarity rule 5).

The split does NOT make the dispatch execute — every fire-action is a Claude
SKILL invocation and no script can call one. It makes the dispatch JOINABLE, so
a consumer can match on `dispatch_skill` where prose was neither parseable nor
uniform. These tests pin the three properties that make that safe:

  1. BYTE-FOR-BYTE BACK-COMPAT. The composed strings must equal the seven
     literals that shipped before the split. Two live consumers read
     `fire_dispatch` for display (precheck-cadence-battery) and two existing
     tests assert on its content, so a composer edit that silently reworded an
     imperative would change what an operator is told to run. The literals below
     are copied from the pre-split file and are deliberately NOT generated from
     the composer — a pin generated by the thing it pins asserts nothing.

  2. THE FIELDS ARE STRUCTURED, not prose. `dispatch_skill` must be a bare slash
     name, because that is the identifier consumers join on.

  3. THE DERIVATION IS LIVE. Mutating a structured field and re-deriving must
     move `fire_dispatch`. Without this a future refactor could re-freeze the
     prose as a literal and every other assertion here would still pass.

Test 1's negative control (guard-1220) is `test_composer_is_not_identity_on_its
_inputs`: a composer that ignored its arguments, or one that returned a constant,
would satisfy a same-length/same-type check while breaking every caller.
"""

import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS))

import _cadence_registry as reg  # underscore module — direct import


# The seven strings EXACTLY as they were hand-written before the split
# (, 2026-09-02). Hand-copied on purpose — see docstring point 1.
LEGACY_FIRE_DISPATCH = {
    "fresh-eyes-review": "invoke /fresh-eyes-review --cadence",
    "fresh-eyes-program": "invoke /fresh-eyes-program --cadence",
    "fresh-eyes-tree": "invoke /fresh-eyes-tree --cadence",
    "strategic-scan": "invoke /aspirations-strategic-scan (scan_trigger=time_cadence)",
    "felt-sense": "invoke /felt-sense-checkin --cadence",
    "curriculum": "invoke /curriculum-gates (re-evaluate gates; route to promotion if all pass)",
    "evolution": "invoke /aspirations-evolve",
}


def _by_name():
    return {c["name"]: c for c in reg.cadences()}


# ------------------------------------------------- 1. byte-for-byte back-compat

def test_every_legacy_dispatch_string_is_reproduced_exactly():
    """The composed prose must equal the pre-split literal for all seven."""
    cads = _by_name()
    assert set(cads) == set(LEGACY_FIRE_DISPATCH), (
        "registry roster changed — add the new cadence's legacy string to "
        "LEGACY_FIRE_DISPATCH (or remove the retired one) in the SAME change, "
        "so this pin keeps covering the whole roster"
    )
    for name, want in LEGACY_FIRE_DISPATCH.items():
        assert cads[name]["fire_dispatch"] == want, (
            f"{name}: composed {cads[name]['fire_dispatch']!r} != legacy {want!r}"
        )


def test_composer_is_not_identity_on_its_inputs():
    """NEGATIVE CONTROL (guard-1220): the composer must actually vary.

    A constant-returning or argument-ignoring composer would pass a
    non-empty-string check while breaking every caller, and would make the
    back-compat test above pass only by coincidence of a single entry.
    """
    base = reg._compose_dispatch("/a")
    assert base == "invoke /a"
    assert reg._compose_dispatch("/a", "--x") == "invoke /a --x"
    assert reg._compose_dispatch("/a", "", "note") == "invoke /a (note)"
    assert reg._compose_dispatch("/a", "--x", "note") == "invoke /a --x (note)"
    # all four shapes distinct — no collapsing
    assert len({
        reg._compose_dispatch("/a"),
        reg._compose_dispatch("/a", "--x"),
        reg._compose_dispatch("/a", "", "note"),
        reg._compose_dispatch("/a", "--x", "note"),
    }) == 4
    # a different skill must produce a different line
    assert reg._compose_dispatch("/b") != base


# ------------------------------------------------------- 2. fields are structured

def test_every_entry_carries_a_bare_slash_skill_name():
    """`dispatch_skill` is the identifier consumers join on — keep it bare."""
    for c in reg.cadences():
        skill = c["dispatch_skill"]
        assert skill.startswith("/"), f"{c['name']}: {skill!r} is not a slash name"
        assert " " not in skill, (
            f"{c['name']}: {skill!r} contains a space — args belong in "
            "dispatch_args and prose in dispatch_note, or the field stops "
            "being joinable, which is the whole point of the split"
        )
        assert "invoke" not in skill, (
            f"{c['name']}: {skill!r} still carries the prose verb"
        )
        # args/note are present and are strings (possibly empty)
        assert isinstance(c["dispatch_args"], str)
        assert isinstance(c["dispatch_note"], str)


def test_dispatch_args_and_note_are_not_swapped():
    """Args look like flags; notes are prose. A swap composes to valid-looking
    output ('invoke /x (--cadence)') that no consumer can act on."""
    for c in reg.cadences():
        if c["dispatch_args"]:
            assert c["dispatch_args"].startswith("-"), (
                f"{c['name']}: dispatch_args {c['dispatch_args']!r} is not a flag"
            )
        if c["dispatch_note"]:
            assert not c["dispatch_note"].startswith("-"), (
                f"{c['name']}: dispatch_note {c['dispatch_note']!r} looks like a flag"
            )


# ------------------------------------------------------------ 3. derivation is live

def test_fire_dispatch_tracks_the_structured_fields():
    """Mutate a structured field, re-derive, and the prose must move.

    Guards against a future refactor re-freezing `fire_dispatch` as a per-entry
    literal — every other assertion in this file would still pass if it did.
    """
    entry = dict(_by_name()["evolution"])
    before = entry["fire_dispatch"]
    entry["dispatch_skill"] = "/somewhere-else"
    after = reg._compose_dispatch(
        entry["dispatch_skill"], entry["dispatch_args"], entry["dispatch_note"]
    )
    assert after != before
    assert after == "invoke /somewhere-else"


# ------------------------------------- 4. the first non-print consumer uses it

def _canary():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "cadence_stale_canary_dispatch_test", SCRIPTS / "cadence-stale-canary.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.mark.parametrize("name", sorted(LEGACY_FIRE_DISPATCH))
def test_canary_goal_names_the_exact_skill_call(name):
    """guard-5298's tell was "the only consumer is a print statement". The
    canary is the first consumer that ACTS on the field: the goal it files must
    name the Skill(...) call, not restate prose."""
    mod = _canary()
    cad = _by_name()[name]
    out = mod._file_investigate(name, 3, cad, dry_run=True)
    title = out["payload_title"]
    body = out["payload_description"]
    skill = cad["dispatch_skill"]

    assert f"Skill({skill})" in title, f"{name}: title does not name the call: {title!r}"
    assert f"Skill({skill})" in body
    assert not title.startswith("Investigate:"), (
        f"{name}: still filed as an investigation — the cause is guard-5298 and "
        "executing an investigation re-derives it instead of running the ritual"
    )
    if cad["dispatch_args"]:
        assert cad["dispatch_args"] in title


def test_canary_goal_does_not_reoffer_the_falsified_meter_drop_hypothesis():
    """The tight-zone meter-drop cause was measured FALSE (foxtrot, N=80,
    sweeps_dropped=0 / zone=fresh while 42 goals past due). The canary filed it
    as a co-equal candidate six times; it must now name it as falsified."""
    mod = _canary()
    body = mod._file_investigate(
        "felt-sense", 3, _by_name()["felt-sense"], dry_run=True
    )["payload_description"]
    assert "FALSIFIED" in body
    assert "guard-5298" in body
    # The phrase that made it a live candidate must be gone.
    assert "OR a persistent tight-zone" not in body
    # POSITIVE CONTROL: the body is non-trivial, so the absences above are real
    # absences and not an empty string (guard-2298).
    assert len(body) > 600, f"body suspiciously short ({len(body)} chars)"


def test_canary_falls_back_to_prose_for_a_pre_split_entry():
    """Fail-soft: handed a dict without the structured fields (an old caller or
    a stubbed cadence), the canary must print the prose rather than 'Skill()'."""
    mod = _canary()
    legacy_entry = {
        "name": "legacy", "phase": "0.5z",
        "check_cmd": ["x.sh"], "meter_name": "legacy-cadence",
        "fire_dispatch": "invoke /legacy-ritual --cadence",
    }
    title = mod._file_investigate(
        "legacy", 3, legacy_entry, dry_run=True
    )["payload_title"]
    assert "invoke /legacy-ritual --cadence" in title
    assert "Skill()" not in title
    assert "None" not in title


def test_cadences_returns_copies_so_a_consumer_cannot_poison_the_registry():
    """`cadences()` hands out list(CADENCES); mutating an entry a consumer got
    must not change what the NEXT caller sees for the fields this split adds."""
    first = _by_name()["curriculum"]
    original = first["dispatch_skill"]
    try:
        first["dispatch_skill"] = "/mutated"
        # Same underlying dicts are shared by design (list() is a shallow copy),
        # so this documents CURRENT behaviour rather than asserting isolation —
        # the point is that a future deep-copy change is a deliberate one.
        assert _by_name()["curriculum"]["dispatch_skill"] == "/mutated"
    finally:
        first["dispatch_skill"] = original
    assert _by_name()["curriculum"]["dispatch_skill"] == original
