"""Aspiration-supply gate — daemon-safe, aspiration-level ( / ).

Refuses MANUFACTURED aspirations at the write chokepoint. The idle path
(aspirations-all-blocked B2 → create-aspiration from-self, B6.7 blocker
synthesis, aspirations-complete-review "replacement" generation) is the
lane where an agent with nothing to do invents work. Its quality rules —
"category labels are not evidence", "an empty pool is acceptable", the
interestingness filter — lived only as prose inside a ~1,100-line skill,
and on a real deployment (2026-09-02) they were skipped outright: five
self-generated aspirations in four days restating one idea ("build
analytical frameworks from public data while the API is blocked"),
zero interestingness-filter events logged, three of them stamped
`user_directive` by the replacement path so no gate ever looked.

This module turns the load-bearing judgments into a script-gated decision
that runs inside the daemon's aspiration add endpoint (every creation lane
funnels through it) and is also callable pre-flight from the skill via
`core/scripts/aspiration-supply-gate.py`.

Scope — fires ONLY for self-generated aspirations:
  * `origin_signal` matches a prefix in config `idle_supply.gated_origin_prefixes`
    (all_blocked_gap, idle_fallback, blocker_pattern:, successor:, ...), OR
  * the motivation is successor-shaped ("Replace(s) completed X with Y")
    under ANY origin — that shape is self-generated by construction, and
    stamping it `user_directive` is an origin misattribution (refused).
User-directed, board-derived and pending-question-derived aspirations pass
untouched (`gated: false`).

Checks on a gated aspiration (ALL must hold, else would_block):
  1. `supply_evidence` present with `gap`, `needle`, `checked` (see
     REMEDY_SHAPE) — the generator must state what is missing, what the
     user gets, and what it LOOKED AT to conclude the gap is real.
  2. ≥ N entries of `checked` resolve to things that EXIST (aspiration /
     goal ids in the store, tree node keys, files under the governed roots,
     board post / reasoning-bank / guardrail / hypothesis ids in their
     stores). Category labels and URLs are not referents.
  3. Neither the motivation's first sentence nor `gap` is blocker-shaped
     ("X is human-blocked", "awaiting approval", "until access is
     restored"). A blocked lane is a reason to WAIT, not a reason to build.
  4. Token overlap with every existing aspiration (live ∪ archive) stays
     below `overlap_threshold`. Overlap with an ACTIVE aspiration is
     refused outright ("file goals under <id>"); overlap with a
     completed/retired one is allowed only when that id is among the
     verified `checked` referents — i.e. the generator read the delivered
     work and names what it lacks (consolidate-before-expand rule 5,
     made mechanical).
  5. Per-agent daily cap on self-generated aspirations
     (`max_self_generated_per_agent_per_day`) — the juice-vs-squeeze
     backstop when everything above is overridden.

Public API:
    evaluate(asp, *, existing, tree_keys=None, override_supply=None,
             agent_name="", world_dir=None, project_root=None,
             meta_dir=None, agent_dir=None, config=None, now=None) -> dict

Return shape:
    {"would_block": bool, "gated": bool, "reason": str,
     "failures": [{"check": str, "detail": str}],
     "checks": {...per-check structured output...},
     "overlaps": [{"id", "status", "title", "containment", "shared"}],
     "remedy": str | None, "override_applied"?: str}

Side effects (inside evaluate, both best-effort):
    * override fires AND would have blocked → append one record to
      <world_dir>/aspiration-supply-overrides.jsonl
    * one _gate_log() telemetry record per gated evaluation
      (decision noop for non-gated aspirations)

Daemon safety: reads no env; every path is an explicit argument. Store
reads are plain-text presence scans (no JSON parse of foreign records).
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set

try:
    from _gate_log import log as _gate_log
except Exception:  # pragma: no cover - telemetry is optional
    def _gate_log(*_a, **_k):  # type: ignore[misc]
        return None

GATE_ID = "aspiration-supply-gate"
LEDGER_NAME = "aspiration-supply-overrides.jsonl"

DEFAULT_CONFIG: Dict[str, Any] = {
    "enabled": True,
    # Self-generated lanes. Matched as case-insensitive SUBSTRINGS of
    # origin_signal, not prefixes: one deployment stamped the same idle path
    # eight ways in six days (`all_blocked_gap`, `all-blocked`,
    # `all-blocked: create-aspiration from-self (...)`,
    # `all-blocked-constraint-generation`, `aspirations-all-blocked`,
    # `idea:b2-constraint-aware-aspiration-generation`, `idle_fallback`, and
    # a false `user_directive`). A prefix list would have gated three of them.
    "gated_origin_patterns": [
        "all_blocked",
        "all-blocked",
        "idle_fallback",
        "blocker_pattern",
        "constraint-aware",
        "constraint_aware",
        "successor",
        "replacement",
        "self_gap",
        "strategic_scan",
        "gap_analysis",
    ],
    "overlap_threshold": 0.40,
    # An overlap refusal also needs this many SHARED tokens: a six-word
    # candidate reaches 40% on three incidental words, which is noise. The
    # replay's weakest genuine refusal shared 4 (a "Week 1 scouting" successor
    # against the live coaching aspiration); the strong ones shared 7-8.
    "min_shared_tokens": 4,
    "min_checked_referents": 2,
    "min_gap_chars": 40,
    "min_needle_chars": 30,
    "max_self_generated_per_agent_per_day": 2,
    "min_goals": 1,
}

REMEDY_SHAPE = (
    '"supply_evidence": {'
    '"gap": "<what is MISSING, named concretely — a file, node, capability, or '
    'user-visible outcome that does not exist yet>", '
    '"needle": "<what the user will be able to do/see once this lands>", '
    '"checked": ["<asp-id or g-id you read>", "<tree node key or file path you '
    'looked at>", "<msg-/rb-/guard-/hypothesis id>"]}'
)

# --- Text shape detectors -----------------------------------------------------

_SUCCESSOR_RE = re.compile(
    r"^\s*(replace(s|d|ment( of| for)?)?|succeed(s|ed)?|successor (to|of|for)|"
    r"follow[- ]?on (to|for))\s+(the\s+)?(completed|finished|closed|retired)\b",
    re.IGNORECASE,
)
_BLOCKER_RE = re.compile(
    r"\b(human[- ]blocked|is blocked|are blocked|blocked on|blocked by|"
    r"blocked until|awaiting|waiting (for|on)|pending (approval|authori[sz]ation|"
    r"credentials|access|consent)|not (yet )?authori[sz]ed|"
    r"(until|when|once|after) [^.;]{0,60}(restored|approved|granted|"
    r"authori[sz]ed|available|unblocked|arrives?|lands?))\b",
    re.IGNORECASE,
)
_PLACEHOLDER_RE = re.compile(r"(\bTBD\b|\bTODO\b|<[^>]{1,60}>|\.\.\.\s*$|\bN/?A\b)", re.IGNORECASE)
_FIRST_SENTENCE_RE = re.compile(r"^(.*?)(?:[.;!?](?:\s|$)|$)", re.DOTALL)

# --- Referent classification --------------------------------------------------

_ASP_RE = re.compile(r"^asp-\d{3,}$")
_GOAL_RE = re.compile(r"^g-\d{3,}-\d{2,4}$")
_MSG_RE = re.compile(r"^msg-\d{8}-\d{6}-[a-z0-9-]+$")
_RB_RE = re.compile(r"^rb-\d+$")
_GUARD_RE = re.compile(r"^guard-\d+$")
_SIG_RE = re.compile(r"^sig-\d+$")
_PQ_RE = re.compile(r"^pq-[a-z0-9][a-z0-9-]*$")
_HYP_RE = re.compile(r"^\d{4}-\d{2}-\d{2}_[a-z0-9][a-z0-9-]*$")
_URL_RE = re.compile(r"^[a-z][a-z0-9+.-]*://", re.IGNORECASE)
_TREE_KEY_RE = re.compile(r"^[a-z0-9][a-z0-9-]{2,}$")
_PATHISH_RE = re.compile(r"(/|\\|\.[a-z0-9]{1,5}$)", re.IGNORECASE)

# --- Tokenizer ----------------------------------------------------------------

_TOKEN_RE = re.compile(r"[a-z0-9][a-z0-9.+_-]*")
_STOPWORDS: Set[str] = {
    # function words
    "the", "and", "for", "with", "from", "into", "onto", "this", "that", "then",
    "than", "them", "they", "their", "there", "these", "those", "when", "where",
    "what", "which", "while", "who", "whom", "why", "how", "also", "only", "just",
    "over", "under", "after", "before", "because", "about", "have", "has", "had",
    "does", "did", "done", "will", "would", "could", "should", "can", "may",
    "might", "must", "not", "but", "are", "was", "were", "been", "being", "its",
    "our", "your", "you", "each", "every", "all", "any", "some", "more", "most",
    "other", "such", "very", "via", "per", "own", "off", "out", "yet", "still",
    "here", "now", "one", "two", "three", "first", "second", "next", "last",
    "same", "both", "either", "neither", "between", "within", "without",
    "across", "through", "during", "against", "toward", "towards", "around",
    "along", "among", "upon", "until", "since", "once", "again", "back",
    "using", "use", "used", "uses", "make", "makes", "made", "making", "get",
    "gets", "got", "keep", "keeps", "kept", "let", "lets", "put", "puts", "set",
    "sets", "take", "takes", "took", "give", "gives", "gave", "come", "comes",
    "came", "become", "becomes", "became", "need", "needs", "needed", "want",
    "wants", "wanted", "able", "allow", "allows", "allowed", "enable",
    "enables", "enabled", "ensure", "ensures", "provide", "provides",
    "provided", "include", "includes", "including", "instead", "rather",
    "however", "therefore", "thus", "hence", "well", "even", "much", "many",
    "less", "least", "few", "several", "various", "another", "others",
    # generic supply/planning vocabulary — poor discriminators between
    # aspirations; every manufactured candidate carries them.
    "build", "builds", "built", "building", "create", "creates", "created",
    "creating", "design", "designs", "designed", "implement", "implements",
    "implemented", "implementation", "plan", "plans", "planning", "develop",
    "develops", "developed", "development", "establish", "establishes",
    "generate", "generates", "generated", "produce", "produces", "produced",
    "deliver", "delivers", "delivered", "support", "supports", "supported",
    "improve", "improves", "improved", "improvement", "improvements",
    "reusable", "actionable", "immediately", "focus", "focused", "focuses",
    "require", "requires", "required", "requiring", "ongoing", "existing",
    "current", "currently", "new", "work", "works", "working", "system",
    "systems", "goal", "goals", "aspiration", "aspirations", "sub-goals",
    "subgoals", "file", "files", "filed", "replace", "replaces", "replaced",
    "completed", "complete", "completes", "done", "finished", "based",
    "specific", "general", "overall", "ready", "later", "early", "long",
    "short", "high", "low", "full", "part", "parts", "level", "levels",
    "human", "user", "users", "agent", "agents", "operator", "self",
}


def _stem(tok: str) -> str:
    """Crude plural fold. Only ever used to compare two texts through the same
    function, so consistency matters more than linguistic accuracy."""
    if len(tok) > 4 and tok.endswith("ies"):
        return tok[:-3] + "y"
    if len(tok) > 5 and tok.endswith(("ches", "shes", "sses", "xes", "zes")):
        return tok[:-2]
    if len(tok) > 3 and tok.endswith("s") and not tok.endswith("ss"):
        return tok[:-1]
    return tok


def tokens(text: Any) -> Set[str]:
    """Distinctive lowercase tokens of a text: stopwords removed, crude stem."""
    if not isinstance(text, str) or not text:
        return set()
    out: Set[str] = set()
    for raw in _TOKEN_RE.findall(text.lower()):
        tok = raw.strip(".+_-")
        if len(tok) < 3 or tok in _STOPWORDS:
            continue
        out.add(_stem(tok))
    return out


def _aspiration_tokens(asp: Dict[str, Any], *, include_goals: bool) -> Set[str]:
    toks = tokens(asp.get("title")) | tokens(asp.get("motivation"))
    se = asp.get("supply_evidence")
    if isinstance(se, dict):
        toks |= tokens(se.get("gap"))
    if include_goals:
        for g in asp.get("goals") or []:
            if isinstance(g, dict):
                toks |= tokens(g.get("title"))
    return toks


def containment(candidate: Set[str], existing: Set[str]) -> float:
    """Fraction of the candidate's distinctive tokens already present in `existing`."""
    if not candidate:
        return 0.0
    return len(candidate & existing) / float(len(candidate))


# --- Store helpers (plain-text presence scans; never parse foreign records) ---

def read_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Read a JSONL store leniently. Missing file → []. Bad lines skipped."""
    out: List[Dict[str, Any]] = []
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if isinstance(rec, dict):
                    out.append(rec)
    except OSError:
        return out
    return out


def load_existing(world_dir: Path, *, agent_dirs: Iterable[Path] = ()) -> List[Dict[str, Any]]:
    """Live ∪ archive aspirations of the world queue (+ optional agent queues)."""
    world_dir = Path(world_dir)
    recs = read_jsonl(world_dir / "aspirations.jsonl")
    recs += read_jsonl(world_dir / "aspirations-archive.jsonl")
    for ad in agent_dirs:
        recs += read_jsonl(Path(ad) / "aspirations.jsonl")
        recs += read_jsonl(Path(ad) / "aspirations-archive.jsonl")
    return recs


def load_tree_keys(world_dir: Path) -> Set[str]:
    """Node keys of the knowledge-tree index. Fail-open to an empty set."""
    try:
        import yaml  # local import: keeps the module importable without PyYAML
        with open(Path(world_dir) / "knowledge" / "tree" / "_tree.yaml", "r",
                  encoding="utf-8") as fh:
            doc = yaml.safe_load(fh) or {}
        nodes = doc.get("nodes") or {}
        return {str(k) for k in nodes.keys()}
    except Exception:
        return set()


def _id_in_file(path: Optional[Path], ref: str) -> bool:
    if path is None:
        return False
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return re.search(r'"id"\s*:\s*"' + re.escape(ref) + r'"', text) is not None


def _id_in_dir(dir_path: Optional[Path], ref: str, glob: str = "*.jsonl") -> bool:
    if dir_path is None:
        return False
    try:
        for p in sorted(Path(dir_path).glob(glob)):
            if _id_in_file(p, ref):
                return True
    except OSError:
        return False
    return False


def _resolve_pathish(ref: str, *, world_dir: Optional[Path], meta_dir: Optional[Path],
                     project_root: Optional[Path], agent_dir: Optional[Path]) -> Optional[Path]:
    raw = ref.strip().replace("\\", "/")
    if not raw:
        return None
    p = Path(raw)
    if p.is_absolute():
        return p
    if raw.startswith("world/") and world_dir is not None:
        return Path(world_dir) / raw[len("world/"):]
    if raw.startswith("meta/") and meta_dir is not None:
        return Path(meta_dir) / raw[len("meta/"):]
    if project_root is not None:
        cand = Path(project_root) / raw
        if cand.exists():
            return cand
    if agent_dir is not None:
        cand = Path(agent_dir) / raw
        if cand.exists():
            return cand
    if world_dir is not None:
        # A tree file cited tree-relative ("<category>/<node>.md") is the natural
        # citation form — measured 2026-09-02: a deployment cited two real tree
        # files that way and was refused twice before it wrote the full
        # "<world>/knowledge/tree/…" path.
        for cand in (Path(world_dir) / raw, Path(world_dir) / "knowledge" / "tree" / raw):
            if cand.exists():
                return cand
    if meta_dir is not None:
        cand = Path(meta_dir) / raw
        if cand.exists():
            return cand
    return Path(project_root) / raw if project_root is not None else p


def verify_referent(ref: Any, *, existing_ids: Set[str], tree_keys: Set[str],
                    world_dir: Optional[Path], meta_dir: Optional[Path],
                    project_root: Optional[Path], agent_dir: Optional[Path]) -> Dict[str, Any]:
    """Classify one `checked` entry and test whether it exists."""
    if not isinstance(ref, str) or not ref.strip():
        return {"ref": ref, "kind": "invalid", "verified": False,
                "note": "not a string"}
    r = ref.strip()
    wd = Path(world_dir) if world_dir else None
    if _URL_RE.match(r):
        return {"ref": r, "kind": "url", "verified": False,
                "note": "a web source is not a referent — cite what is missing HERE"}
    if _ASP_RE.match(r) or _GOAL_RE.match(r):
        ok = r in existing_ids
        return {"ref": r, "kind": "aspiration" if r.startswith("asp-") else "goal",
                "verified": ok, "note": None if ok else "id not present in the aspiration store"}
    if _MSG_RE.match(r):
        ok = _id_in_dir(wd / "board" if wd else None, r)
        return {"ref": r, "kind": "board_post", "verified": ok,
                "note": None if ok else "post id not found in world/board/*.jsonl"}
    if _RB_RE.match(r):
        ok = _id_in_file(wd / "reasoning-bank.jsonl" if wd else None, r)
        return {"ref": r, "kind": "reasoning_bank", "verified": ok,
                "note": None if ok else "id not found in reasoning-bank.jsonl"}
    if _GUARD_RE.match(r):
        ok = _id_in_file(wd / "guardrails.jsonl" if wd else None, r)
        return {"ref": r, "kind": "guardrail", "verified": ok,
                "note": None if ok else "id not found in guardrails.jsonl"}
    if _SIG_RE.match(r):
        ok = _id_in_file(wd / "pattern-signatures.jsonl" if wd else None, r)
        return {"ref": r, "kind": "pattern_signature", "verified": ok,
                "note": None if ok else "id not found in pattern-signatures.jsonl"}
    if _HYP_RE.match(r):
        ok = _id_in_file(wd / "pipeline.jsonl" if wd else None, r)
        return {"ref": r, "kind": "hypothesis", "verified": ok,
                "note": None if ok else "id not found in pipeline.jsonl"}
    if _PQ_RE.match(r):
        ok = False
        if agent_dir is not None:
            pq = Path(agent_dir) / "session" / "pending-questions.yaml"
            try:
                ok = re.search(r"\b" + re.escape(r) + r"\b", pq.read_text(encoding="utf-8")) is not None
            except OSError:
                ok = False
        return {"ref": r, "kind": "pending_question", "verified": ok,
                "note": None if ok else "id not found in session/pending-questions.yaml"}
    if _PATHISH_RE.search(r):
        p = _resolve_pathish(r, world_dir=wd, meta_dir=Path(meta_dir) if meta_dir else None,
                             project_root=Path(project_root) if project_root else None,
                             agent_dir=Path(agent_dir) if agent_dir else None)
        ok = bool(p is not None and p.exists())
        return {"ref": r, "kind": "path", "verified": ok,
                "note": None if ok else f"path does not exist ({p})"}
    if _TREE_KEY_RE.match(r):
        ok = r in tree_keys
        return {"ref": r, "kind": "tree_node", "verified": ok,
                "note": None if ok else "not a node key in knowledge/tree/_tree.yaml"}
    return {"ref": r, "kind": "unrecognized", "verified": False,
            "note": "not an id, node key, or path — category labels are not referents"}


# --- Gating predicate ---------------------------------------------------------

def origin_is_self_generated(origin: Any, cfg: Dict[str, Any]) -> bool:
    """True when origin_signal names an idle/self-generated lane (substring match)."""
    o = str(origin or "").strip().lower()
    if not o:
        return False
    patterns = [str(p).lower() for p in (cfg.get("gated_origin_patterns") or [])]
    return any(p and p in o for p in patterns)


def is_gated(asp: Dict[str, Any], cfg: Dict[str, Any]) -> Dict[str, Any]:
    origin = str(asp.get("origin_signal") or "").strip()
    motivation = str(asp.get("motivation") or "")
    by_origin = origin_is_self_generated(origin, cfg)
    successor = bool(_SUCCESSOR_RE.match(motivation))
    misattributed = successor and not by_origin and origin.startswith("user_directive")
    return {
        "gated": by_origin or successor,
        "by_origin": by_origin,
        "successor_shaped": successor,
        "origin_misattributed": misattributed,
        "origin_signal": origin or None,
    }


def _first_sentence(text: str) -> str:
    m = _FIRST_SENTENCE_RE.match(text.strip())
    return (m.group(1) if m else text).strip()


def _today(now: Optional[datetime]) -> str:
    return (now or datetime.now()).strftime("%Y-%m-%d")


# --- Public API ---------------------------------------------------------------

def evaluate(asp: Dict[str, Any], *, existing: Iterable[Dict[str, Any]],
             tree_keys: Optional[Set[str]] = None,
             override_supply: Optional[str] = None,
             agent_name: str = "",
             world_dir: Optional[Path] = None,
             project_root: Optional[Path] = None,
             meta_dir: Optional[Path] = None,
             agent_dir: Optional[Path] = None,
             config: Optional[Dict[str, Any]] = None,
             now: Optional[datetime] = None) -> Dict[str, Any]:
    cfg = dict(DEFAULT_CONFIG)
    if isinstance(config, dict):
        cfg.update({k: v for k, v in config.items() if v is not None})
    existing_list = [e for e in existing if isinstance(e, dict)]
    tree_keys = set(tree_keys or ())
    title = str(asp.get("title") or "")

    gate = is_gated(asp, cfg)
    if not cfg.get("enabled", True) or not gate["gated"]:
        _gate_log(GATE_ID, "noop", payload=title[:120], agent_name=agent_name or None,
                  meta_dir=meta_dir, extra={"gated": False, "origin_signal": gate["origin_signal"]})
        return {"would_block": False, "gated": False, "reason": "not a self-generated aspiration",
                "failures": [], "checks": {"gate": gate}, "overlaps": [], "remedy": None}

    failures: List[Dict[str, str]] = []
    checks: Dict[str, Any] = {"gate": gate}

    # 0. origin misattribution (successor-shaped under user_directive)
    if gate["origin_misattributed"]:
        failures.append({
            "check": "origin_misattributed",
            "detail": ("motivation is successor-shaped (\"replace completed …\") but "
                       "origin_signal claims user_directive; a replacement for completed "
                       "work is self-generated — stamp origin_signal successor:<asp-id>"),
        })

    # 1. supply_evidence shape
    se = asp.get("supply_evidence")
    gap = needle = ""
    checked_raw: List[Any] = []
    if not isinstance(se, dict):
        failures.append({"check": "supply_evidence_missing",
                         "detail": "self-generated aspiration carries no supply_evidence object"})
    else:
        gap = str(se.get("gap") or "").strip()
        needle = str(se.get("needle") or "").strip()
        checked_raw = list(se.get("checked") or []) if isinstance(se.get("checked"), list) else []
        if len(gap) < int(cfg["min_gap_chars"]) or _PLACEHOLDER_RE.search(gap):
            failures.append({"check": "gap_unspecified",
                             "detail": f"supply_evidence.gap must name what is missing in ≥{cfg['min_gap_chars']} chars without placeholders"})
        if len(needle) < int(cfg["min_needle_chars"]) or _PLACEHOLDER_RE.search(needle):
            failures.append({"check": "needle_unspecified",
                             "detail": f"supply_evidence.needle must state the user-visible outcome in ≥{cfg['min_needle_chars']} chars"})
        if needle and gap and needle == gap:
            failures.append({"check": "needle_unspecified",
                             "detail": "supply_evidence.needle repeats gap verbatim"})

    # 2. checked referents exist
    existing_ids: Set[str] = set()
    for e in existing_list:
        if e.get("id"):
            existing_ids.add(str(e["id"]))
        for g in e.get("goals") or []:
            if isinstance(g, dict) and g.get("id"):
                existing_ids.add(str(g["id"]))
    referents = [verify_referent(r, existing_ids=existing_ids, tree_keys=tree_keys,
                                 world_dir=world_dir, meta_dir=meta_dir,
                                 project_root=project_root, agent_dir=agent_dir)
                 for r in checked_raw]
    verified_refs = {r["ref"] for r in referents if r["verified"]}
    checks["referents"] = referents
    min_refs = int(cfg["min_checked_referents"])
    if len(verified_refs) < min_refs:
        failures.append({
            "check": "referents_unverified",
            "detail": (f"{len(verified_refs)} of {len(referents)} checked referents exist "
                       f"(need ≥{min_refs}): "
                       + "; ".join(f"{r['ref']!s} → {r['note']}" for r in referents if not r["verified"])[:400]
                       if referents else f"supply_evidence.checked is empty (need ≥{min_refs} existing referents)"),
        })

    # 3. blocker-shaped motivation / gap. An `Unblock:` aspiration (the
    # cognitive primitive, incl. B6.7 blocker-pattern synthesis) targets the
    # blocker ITSELF, which is the opposite of manufacturing adjacent work —
    # it is exempt here and still owes real referents (the blocked goal ids).
    motivation = str(asp.get("motivation") or "")
    first = _first_sentence(motivation)
    blocker_hits = []
    is_unblock = title.strip().lower().startswith("unblock:")
    if not is_unblock:
        if first and _BLOCKER_RE.search(first):
            blocker_hits.append(("motivation", first))
        if gap and _BLOCKER_RE.search(gap):
            blocker_hits.append(("gap", gap))
    checks["blocker_shaped"] = [{"field": f, "text": t[:160]} for f, t in blocker_hits]
    if blocker_hits:
        failures.append({
            "check": "blocker_as_gap",
            "detail": ("the stated reason is a BLOCKER, not a gap ("
                       + "; ".join(f"{f}: \"{t[:90]}\"" for f, t in blocker_hits)
                       + ") — a blocked lane is a reason to wait for the unblock, not to manufacture "
                         "adjacent work; if something is genuinely missing, name THAT in gap"),
        })

    # 4. overlap with the archive
    cand_tokens = _aspiration_tokens(asp, include_goals=True)
    overlaps: List[Dict[str, Any]] = []
    for e in existing_list:
        ex_tokens = _aspiration_tokens(e, include_goals=False)
        c = containment(cand_tokens, ex_tokens)
        if c > 0:
            overlaps.append({
                "id": e.get("id"), "status": e.get("status"),
                "title": str(e.get("title") or "")[:120],
                "containment": round(c, 3),
                "shared": sorted(cand_tokens & ex_tokens),
            })
    overlaps.sort(key=lambda o: o["containment"], reverse=True)
    top = overlaps[:3]
    thr = float(cfg["overlap_threshold"])
    min_shared = int(cfg.get("min_shared_tokens") or 0)
    for o in top:
        if o["containment"] < thr or len(o["shared"]) < min_shared:
            continue
        active = str(o.get("status") or "active") == "active"
        if active:
            failures.append({
                "check": "overlaps_active",
                "detail": (f"{o['containment']:.0%} of this candidate's distinctive tokens already "
                           f"belong to ACTIVE {o['id']} \"{o['title']}\" (shared: {', '.join(o['shared'][:8])}) "
                           f"— file goals under {o['id']} instead of a new aspiration"),
            })
            break
        if o["id"] not in verified_refs:
            failures.append({
                "check": "overlaps_archived",
                "detail": (f"{o['containment']:.0%} overlap with {o.get('status')} {o['id']} "
                           f"\"{o['title']}\" (shared: {', '.join(o['shared'][:8])}) — building on "
                           f"finished work is fine only when you cite it: add {o['id']} to "
                           f"supply_evidence.checked and state in gap what it delivered and what is missing"),
            })
            break

    # 5. per-agent daily cap
    today = _today(now)
    made_today = 0
    for e in existing_list:
        if not origin_is_self_generated(e.get("origin_signal"), cfg):
            continue
        if str(e.get("created_at") or "")[:10] != today:
            continue
        by = e.get("created_by_agent")
        if by and agent_name and by != agent_name:
            continue
        made_today += 1
    cap = int(cfg["max_self_generated_per_agent_per_day"])
    checks["self_generated_today"] = made_today
    if cap > 0 and made_today >= cap:
        failures.append({
            "check": "daily_cap",
            "detail": (f"{made_today} self-generated aspiration(s) already filed today by "
                       f"{agent_name or 'this agent'} (cap {cap}/day) — the idle path is manufacturing; "
                       "go quiet instead"),
        })

    # 6. a first goal. An aspiration filed with no goals creates NO work: the
    # selector has nothing to pick, the loop stays all-blocked, and the idle
    # path runs again (measured 2026-09-02: the first gate-clean aspiration on
    # a deployment landed with "0 pending, 0 done of 0" and the loop slept).
    goals = asp.get("goals") if isinstance(asp.get("goals"), list) else []
    min_goals = int(cfg.get("min_goals", 1) or 0)
    checks["goals"] = len(goals)
    if min_goals > 0 and len(goals) < min_goals:
        failures.append({
            "check": "no_goals",
            "detail": (f"self-generated aspiration carries {len(goals)} goal(s) (need ≥{min_goals}) — "
                       "an aspiration without a first verifiable goal is a title, not work; file "
                       "the first goal(s) in the same record (title, priority, participants, "
                       "verification.outcomes)"),
        })

    remedy = None
    if failures:
        remedy = ("Either drop the candidate (an empty pool is the expected outcome when nothing "
                  "verifiable is missing — the loop goes quiet) or fix the record: " + REMEDY_SHAPE
                  + '; and "goals": [<at least one concrete, verifiable first goal>]')

    override_applied = None
    would_block = bool(failures)
    decision = "block" if would_block else "pass"
    if would_block and override_supply:
        would_block = False
        override_applied = override_supply
        decision = "override"
        _append_ledger(world_dir, {
            "ts": (now or datetime.now()).isoformat(timespec="seconds"),
            "gate": GATE_ID, "agent": agent_name or None, "title": title,
            "origin_signal": gate["origin_signal"], "justification": override_supply,
            "failures": [f["check"] for f in failures],
        })

    _gate_log(GATE_ID, decision, trigger_matched=(failures[0]["check"] if failures else None),
              payload=title[:120], override_reason=override_supply if override_applied else None,
              agent_name=agent_name or None, meta_dir=meta_dir,
              extra={"gated": True, "origin_signal": gate["origin_signal"],
                     "failures": [f["check"] for f in failures],
                     "top_overlap": (top[0]["id"] if top else None),
                     "top_containment": (top[0]["containment"] if top else 0.0),
                     "self_generated_today": made_today})

    result: Dict[str, Any] = {
        "would_block": would_block, "gated": True,
        "reason": ("pass" if not failures else "; ".join(f["detail"] for f in failures)),
        "failures": failures, "checks": checks, "overlaps": top, "remedy": remedy,
    }
    if override_applied:
        result["override_applied"] = override_applied
    return result


def _append_ledger(world_dir: Optional[Path], record: Dict[str, Any]) -> None:
    if world_dir is None:
        return
    try:
        with open(Path(world_dir) / LEDGER_NAME, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")
    except OSError:
        pass
