"""_framework_origin — does THIS deployment take its framework from somewhere else?

A deployment whose registry entry (core/config/environments/<ENVIRONMENT_ID>.yaml)
carries `framework_origin: <env-id>` receives core/, .claude/, mind_api/ and
CLAUDE.md through the promotion train (`.claude/rules/promotion-cycle.md`,
`core/config/conventions/pull-promotion.md` § g) and does not edit them locally.
Two consumers refuse local framework writes on such a deployment:

  path-resolution-hook.py            PreToolUse Write/Edit/MultiEdit — the write
                                     never lands, and the refusal says where the
                                     change goes instead
  check-framework-origin-writes.py   pre-commit Gate 15 — the Bash backstop
                                     (`cat >`, `sed -i`, heredocs walk past L1)

WHY (measured 2026-08-30, coach@zc-03, the third Mind deployment, run by
small-model Bodies): a Body executing /curriculum-gates used edit_file THREE
times on `.claude/skills/curriculum-gates/SKILL.md` to write its step RESULTS
under the step headings — "Gates evaluated: configured=false, all_passed=false,
gates=[] (15.2 complete)" — the skill file as a worksheet. Nothing refused it:
framework paths are agent-editable by design on the dev origin, and the
promotion cycle's "downstream refuses dev work" was honor-system. Left alone the
edit would have been loop-committed and collided with the next upstream merge.

Both consumers exempt a DESTINATION-OWNED forged skill body (is_forged_skill_body
below) — the promotion train does not carry those, so refusing them left a forged
skill with no home on any downstream deployment.

Absent field (or one naming the deployment itself) = this deployment IS a
framework origin: local framework edits stay allowed and git-audited, exactly as
before. Every existing registry entry keeps its behaviour; only an entry that
opts in changes anything. Fail-open throughout: an unreadable registry, an
unknown ENVIRONMENT_ID or an import error all resolve to "origin" (no refusal)
— the dangerous error is blocking the dev loop, never letting one edit through.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# Mirrors promotion-preflight.py FRAMEWORK_PATHS at the top level — the unit the
# promotion train carries. agents/, readme/, .env* and the world are not
# framework and stay writable.
FRAMEWORK_PREFIXES = ("core/", ".claude/", "mind_api/")
FRAMEWORK_FILES = frozenset({"CLAUDE.md"})
# Runtime output that happens to live under a framework prefix — never framework.
RUNTIME_PREFIXES = (
    "core/logs/", "core/.pycache/", "core/scripts/.python-shim/", "mind_api/state/",
)


def is_framework_path(rel_path: str) -> bool:
    """True for a repo-relative path the promotion train owns."""
    rel = str(rel_path or "").replace("\\", "/")
    while rel.startswith("./"):
        rel = rel[2:]
    rel = rel.lstrip("/")
    if not rel:
        return False
    if rel in FRAMEWORK_FILES:
        return True
    if rel.startswith(RUNTIME_PREFIXES):
        return False
    return rel.startswith(FRAMEWORK_PREFIXES)


# A DESTINATION-OWNED skill dir under .claude/skills/ is not part of the unit the
# promotion train carries, and the rest of the system already models it that way:
# core/config/seed-manifest.yaml excludes forged skills from the seed ("domain-
# specific, generated by /forge-skill at runtime"), _seed_engine._is_protected_dest_skill
# refuses to delete them as orphans ("Un-forging a skill must be a deliberate act,
# never a transplant side-effect"), and promotion-preflight.py's bucket() keeps
# .claude/skills/** out of the blocking core bucket entirely (target-only skills
# print as "usually domain/forged (deployment-local)"). Only THIS module disagreed:
# its blanket ".claude/" prefix swept forged bodies in as collateral of a refusal
# aimed at BASE skills, so on a framework_origin deployment a forged skill body
# could not land anywhere either runtime loads. Measured 2026-09-05, coach@zc-03:
# Write(.claude/skills/query-scouting-matchups/SKILL.md) refused, the registry row
# written anyway, zero skill forged (, rb-10227). The carve-out below
# restores agreement with the machinery around it; it does not invent an exception.
SKILLS_ROOT = ".claude/skills/"
FORGED_TAG_SCAN_LINES = 40


def is_forged_skill_body(rel_path: str, project_root) -> bool:
    """True for a path under a DESTINATION-OWNED skill dir — one this deployment
    forged, not one the promotion train planted.

    Two accepting shapes, both decided from the local filesystem alone. The hook
    runs on every Write, so a git or registry call here would cost more than it
    buys — and world/forged-skills.yaml cannot help at CREATION time regardless,
    since the row is written after the body (that ordering is what produced the
    phantom registry row in the measured run):

      skill dir absent          -> a skill upstream does not have; nothing to clobber
      SKILL.md carries forged:  -> a body this deployment owns; revising it is local

    Anything else is NOT exempt — most importantly an EXISTING base skill's dir,
    which is exactly what the measured worksheet edit targeted
    (.claude/skills/curriculum-gates/SKILL.md, 2026-08-30, coach@zc-03).

    FAIL DIRECTION IS THE OPPOSITE OF THIS MODULE'S OTHER HELPERS, DELIBERATELY.
    framework_origin() fails OPEN because its dangerous error is blocking the dev
    loop. Here the dangerous error is a wrong ALLOW: it re-opens the worksheet hole
    the refusal exists to close. So an unreadable body, a malformed path, or any
    OSError returns False (refuse). Do not "tidy" the two directions into one.
    """
    rel = str(rel_path or "").replace("\\", "/")
    while rel.startswith("./"):
        rel = rel[2:]
    rel = rel.lstrip("/")
    if not rel.startswith(SKILLS_ROOT):
        return False
    name = rel[len(SKILLS_ROOT):].split("/", 1)[0]
    if not name or name in (".", ".."):
        return False
    try:
        skills_root = Path(project_root) / ".claude" / "skills"
        # "Dir absent" is the one branch that fails toward ALLOW, so first prove the
        # root is a real checkout. Without this, an unresolvable project_root makes
        # every skill path look brand-new and exempts the whole surface.
        if not skills_root.is_dir():
            return False
        skill_dir = skills_root / name
        if not skill_dir.is_dir():
            return True  # a skill this deployment is creating; upstream has none
        body = skill_dir / "SKILL.md"
        if not body.is_file():
            return True  # dir without a body (the `mkdir -p` residue) — still new
        head = body.read_text(encoding="utf-8", errors="replace").splitlines()[:FORGED_TAG_SCAN_LINES]
    except Exception:  # noqa: BLE001 — unreadable means REFUSE here, not allow
        return False
    return any(re.match(r"^forged:\s*true\b", line.strip()) for line in head)


def self_env_id() -> str | None:
    """ENVIRONMENT_ID of this checkout: the env var, else .env.local via _paths."""
    env_id = os.environ.get("ENVIRONMENT_ID", "").strip()
    if env_id:
        return env_id
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _paths import ENVIRONMENT_ID  # type: ignore
        return str(ENVIRONMENT_ID).strip() if ENVIRONMENT_ID else None
    except Exception:  # noqa: BLE001 — fail open
        return None


def framework_origin(project_root, env_id: str | None = None) -> str | None:
    """The env-id this deployment takes its framework FROM, or None when it is an
    origin itself (field absent, blank, self-referencing, or anything unreadable)."""
    try:
        env_id = (env_id or self_env_id() or "").strip()
        if not env_id:
            return None
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _peer_registry import load_env_registry  # type: ignore
        registry = load_env_registry(Path(project_root) / "core" / "config" / "environments")
        origin = str((registry.get(env_id) or {}).get("framework_origin") or "").strip()
        if not origin or origin == env_id:
            return None
        return origin
    except Exception:  # noqa: BLE001 — fail open
        return None
