#!/usr/bin/env python3
"""Compact checkpoint slot restoration — restore all WM slots from checkpoint.

Called by Phase -0.5c of the aspirations loop (via compact-restore-slots.sh).
Reads compact-checkpoint.yaml, restores all_slots to working memory with
intelligent merge logic, and outputs a summary.

Merge rules:
  - Array slots: extend (don't overwrite) if WM already has items
  - Map slots: merge keys (checkpoint values take precedence)
  - Scalar slots: overwrite with checkpoint value
  - Skip list: archived_context (stale by definition)
  - Restore slot_meta timestamps for age tracking accuracy
"""

import json
import sys
from datetime import datetime

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import yaml

from _paths import AGENT_DIR
from wm import read_wm, write_wm

CHECKPOINT_PATH = AGENT_DIR / "session" / "compact-checkpoint.yaml"

# Slots to skip during restoration (stale or regenerated by the loop)
SKIP_SLOTS = {"archived_context"}


def now_iso():
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


def main():
    if not CHECKPOINT_PATH.exists():
        print("no checkpoint")
        return

    checkpoint = yaml.safe_load(CHECKPOINT_PATH.read_text(encoding="utf-8")) or {}
    all_slots = checkpoint.get("all_slots") or {}
    saved_meta = checkpoint.get("slot_meta") or {}

    if not all_slots:
        print("no slots in checkpoint")
        return

    wm = read_wm()
    if not wm:
        print("ERROR: Working memory not initialized", file=sys.stderr)
        sys.exit(1)

    wm_slots = wm.setdefault("slots", {})
    wm_meta = wm.setdefault("slot_meta", {})

    restored = []
    skipped = []
    merged = []

    for slot_name, saved_value in all_slots.items():
        # Skip list
        if slot_name in SKIP_SLOTS:
            skipped.append(slot_name)
            continue

        # Skip null/empty values from checkpoint
        if saved_value is None:
            continue
        if isinstance(saved_value, list) and not saved_value:
            continue
        if isinstance(saved_value, dict) and not any(v is not None for v in saved_value.values()):
            continue

        current = wm_slots.get(slot_name)

        # Merge logic
        if isinstance(saved_value, list) and isinstance(current, list) and current:
            # Array merge: extend with checkpoint items not already present
            existing_set = {
                json.dumps(item, sort_keys=True, default=str) if isinstance(item, dict) else str(item)
                for item in current
            }
            added = 0
            for item in saved_value:
                key = json.dumps(item, sort_keys=True, default=str) if isinstance(item, dict) else str(item)
                if key not in existing_set:
                    current.append(item)
                    existing_set.add(key)
                    added += 1
            if added:
                merged.append(f"{slot_name}(+{added})")
        elif isinstance(saved_value, dict) and isinstance(current, dict) and current:
            # Map merge: checkpoint values take precedence for non-null keys
            for k, v in saved_value.items():
                if v is not None:
                    current[k] = v
            merged.append(slot_name)
        else:
            # Scalar or replacing empty: direct overwrite
            wm_slots[slot_name] = saved_value
            restored.append(slot_name)

        # Restore slot_meta timestamps
        if slot_name in saved_meta:
            sm = saved_meta[slot_name]
            wm_meta[slot_name] = {
                "updated_at": sm.get("updated_at") or now_iso(),
                "accessed_at": sm.get("accessed_at") or now_iso(),
                "update_count": sm.get("update_count", 0),
            }

    # Restore top-level WM keys from checkpoint
    top_restored = []
    for key in ["goals_completed_this_session", "aspiration_touched_last", "last_goal_category"]:
        val = checkpoint.get(key)
        if val is not None and val != "" and val != []:
            wm[key] = val
            top_restored.append(key)

    write_wm(wm)

    # Output summary for the LLM
    parts = []
    if restored:
        parts.append(f"restored: {', '.join(restored)}")
    if merged:
        parts.append(f"merged: {', '.join(merged)}")
    if skipped:
        parts.append(f"skipped: {', '.join(skipped)}")
    if top_restored:
        parts.append(f"top-level: {', '.join(top_restored)}")

    total = len(restored) + len(merged)
    summary = f"{total} slots recovered"
    if parts:
        summary += f" ({'; '.join(parts)})"
    print(summary)


if __name__ == "__main__":
    main()
