#!/usr/bin/env python3
"""Compact checkpoint slot restoration — restore all WM slots from checkpoint.

Called by Phase -0.5c of the aspirations loop (via compact-restore-slots.sh).
Reads compact-checkpoint.yaml, restores all_slots to working memory with
intelligent merge logic, and outputs a summary.

Merge rules:
  - Array slots: extend (don't overwrite) if WM already has items
  - Map slots: merge keys (checkpoint values take precedence)
  - Scalar slots: overwrite with checkpoint value
  - Skip list: archived_context (stale by definition)
  - Restore slot_meta timestamps for age tracking accuracy
"""

import json
import sys
from datetime import datetime

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import yaml

from _paths import AGENT_DIR, assert_agent_dir
from wm import WM_PATH, read_wm, write_wm

# : fail loud at import time if MIND_AGENT unset; replaces the
# opaque `None / "session"` TypeError class the next line would otherwise raise.
assert_agent_dir("compact-restore-slots")

CHECKPOINT_PATH = AGENT_DIR / "session" / "compact-checkpoint.yaml"


def _is_checkpoint_stale(checkpoint_path, wm_path):
    """True if wm.yaml is fresher than checkpoint — restore would regress.

    g-115-684 fix. Closes the rare-but-significant window where the LLM
    completes an iteration successfully INSIDE the same turn that began
    after PreCompact wrote the checkpoint, so by the time Phase -0.5c
    fires on the next loop entry, wm.yaml carries newer state (e.g.
    counted_goals_this_session has a goal not in the checkpoint's
    loop_state). Running the merge logic would silently drop that goal
    from the counter, double-counting it on the next learning-gate.

    Observed canonical case: zeta session 28 iter 6 (2026-05-13) had
    checkpoint mtime 03:08:38 (mid-iter-5 PreCompact) but wm.yaml mtime
    03:21:55 with counted_goals=[g-115-681, g-115-666]. Checkpoint's
    loop_state had counted=[g-115-681] only (missing g-115-666).
    Resolution at the time: manual delete of stale checkpoint after
    mtime comparison.

    Returns True when wm.yaml strictly newer than checkpoint (the
    regression risk case). Equal mtimes → False (treat as fresh restore).
    Missing files or stat errors → False (fall through to existing
    behavior; fail-open).
    """
    try:
        if not checkpoint_path or not wm_path:
            return False
        if not checkpoint_path.exists() or not wm_path.exists():
            return False
        ck_mtime = checkpoint_path.stat().st_mtime
        wm_mtime = wm_path.stat().st_mtime
        return wm_mtime > ck_mtime
    except OSError:
        return False

# Slots to skip during restoration. Two reasons a slot ends up here:
#   1. Stale by definition (regenerated by the loop) — `archived_context`.
#   2. Latest-wins semantics — restoring an older checkpoint snapshot OVER
#      a newer current value silently reverts cadence stamps and iteration
#      counters. The Map-merge logic at L97-102 unconditionally overwrites
#      current[k] with checkpoint[k] when v is not None, which is wrong for
#      these slots. Documented in  fix (Fix 2), with full incident
#      trace in world/knowledge/tree/system/system-constraints-loop/
#      compact-restore-map-merge-clobber.md ( root cause).
#
# Future dict-shape slot authors: if your slot has timestamp + count fields
# that must reflect the most-recent write across compaction, add it here.
# Heuristic Fix 1 (timestamp-aware merge) is filed as a follow-up Idea goal
# — until it lands, additive SKIP_SLOTS is the safe path.
SKIP_SLOTS = {
    "archived_context",
    "last_felt_sense_checkin",
    "last_fresh_eyes_review",
    "last_fresh_eyes_program_review",
    "last_strategic_scan",
    "loop_state",
    "consolidation_health",
    "portfolio_health_signal",
}


def now_iso():
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


def main():
    if not CHECKPOINT_PATH.exists():
        print("no checkpoint")
        return

    # Freshness gate (): when wm.yaml mtime exceeds checkpoint mtime,
    # the in-process iteration completed after PreCompact, so wm.yaml carries
    # newer state. Running the merge logic here would silently regress
    # counters and slot values. SKIP the restore + return success — the
    # caller (Phase -0.5c) still proceeds to process encoding_queue and
    # delete the stale checkpoint (one-shot consumption).
    if _is_checkpoint_stale(CHECKPOINT_PATH, WM_PATH):
        ck_mtime = CHECKPOINT_PATH.stat().st_mtime
        wm_mtime = WM_PATH.stat().st_mtime
        delta = wm_mtime - ck_mtime
        print(
            f"checkpoint stale (wm.yaml is {delta:.0f}s fresher than checkpoint) — "
            f"restore SKIPPED to prevent loop_state regression (g-115-684)"
        )
        return

    checkpoint = yaml.safe_load(CHECKPOINT_PATH.read_text(encoding="utf-8")) or {}
    all_slots = checkpoint.get("all_slots") or {}
    saved_meta = checkpoint.get("slot_meta") or {}

    if not all_slots:
        print("no slots in checkpoint")
        return

    wm = read_wm()
    if not wm:
        print("ERROR: Working memory not initialized", file=sys.stderr)
        sys.exit(1)

    wm_slots = wm.setdefault("slots", {})
    wm_meta = wm.setdefault("slot_meta", {})

    restored = []
    skipped = []
    merged = []

    for slot_name, saved_value in all_slots.items():
        # Skip list
        if slot_name in SKIP_SLOTS:
            skipped.append(slot_name)
            continue

        # Skip null/empty values from checkpoint
        if saved_value is None:
            continue
        if isinstance(saved_value, list) and not saved_value:
            continue
        if isinstance(saved_value, dict) and not any(v is not None for v in saved_value.values()):
            continue

        current = wm_slots.get(slot_name)

        # Merge logic
        if isinstance(saved_value, list) and isinstance(current, list) and current:
            # Array merge: extend with checkpoint items not already present
            existing_set = {
                json.dumps(item, sort_keys=True, default=str) if isinstance(item, dict) else str(item)
                for item in current
            }
            added = 0
            for item in saved_value:
                key = json.dumps(item, sort_keys=True, default=str) if isinstance(item, dict) else str(item)
                if key not in existing_set:
                    current.append(item)
                    existing_set.add(key)
                    added += 1
            if added:
                merged.append(f"{slot_name}(+{added})")
        elif isinstance(saved_value, dict) and isinstance(current, dict) and current:
            # Map merge with timestamp-aware preference (, Fix 1 of ).
            # Sibling to the SKIP_SLOTS list above (Fix 2, ) — that list
            # names the slots known today to need latest-wins semantics. THIS
            # branch protects FUTURE dict-shape slots whose authors forget to add
            # to SKIP_SLOTS: when both dicts carry an epoch-like field, keep the
            # newer one; when timestamps are missing or ambiguous, fall through
            # to the original checkpoint-wins semantics for backward compat.
            cur_ts = current.get("timestamp") or current.get("updated_at") or current.get("time")
            chk_ts = saved_value.get("timestamp") or saved_value.get("updated_at") or saved_value.get("time")
            if cur_ts and chk_ts and cur_ts >= chk_ts:
                # Current is newer than checkpoint — preserve it. Fill nulls
                # from checkpoint (don't overwrite anything current already has).
                for k, v in saved_value.items():
                    if v is not None and current.get(k) is None:
                        current[k] = v
            else:
                # Current is older OR timestamps missing OR undeterminable.
                # Fall back to original checkpoint-wins for backward compat —
                # SKIP_SLOTS still names the slots where even this is wrong.
                for k, v in saved_value.items():
                    if v is not None:
                        current[k] = v
            merged.append(slot_name)
        else:
            # Scalar or replacing empty: direct overwrite
            wm_slots[slot_name] = saved_value
            restored.append(slot_name)

        # Restore slot_meta timestamps
        if slot_name in saved_meta:
            sm = saved_meta[slot_name]
            wm_meta[slot_name] = {
                "updated_at": sm.get("updated_at") or now_iso(),
                "accessed_at": sm.get("accessed_at") or now_iso(),
                "update_count": sm.get("update_count", 0),
            }

    # Restore top-level WM keys from checkpoint
    top_restored = []
    for key in ["goals_completed_this_session", "aspiration_touched_last", "last_goal_category"]:
        val = checkpoint.get(key)
        if val is not None and val != "" and val != []:
            wm[key] = val
            top_restored.append(key)

    write_wm(wm)

    # Output summary for the LLM
    parts = []
    if restored:
        parts.append(f"restored: {', '.join(restored)}")
    if merged:
        parts.append(f"merged: {', '.join(merged)}")
    if skipped:
        parts.append(f"skipped: {', '.join(skipped)}")
    if top_restored:
        parts.append(f"top-level: {', '.join(top_restored)}")

    total = len(restored) + len(merged)
    summary = f"{total} slots recovered"
    if parts:
        summary += f" ({'; '.join(parts)})"
    print(summary)


if __name__ == "__main__":
    main()
