#!/usr/bin/env python3
"""Compact checkpoint slot restoration — restore all WM slots from checkpoint.

Called by Phase -0.5c of the aspirations loop (via compact-restore-slots.sh).
Reads compact-checkpoint.yaml, restores all_slots to working memory with
intelligent merge logic, and outputs a summary.

Merge rules:
  - Array slots: extend (don't overwrite) if WM already has items
  - Map slots: merge keys (checkpoint values take precedence)
  - Scalar slots: overwrite with checkpoint value
  - Skip list: archived_context (stale by definition)
  - Restore slot_meta timestamps for age tracking accuracy
"""

import json
import sys
from datetime import datetime

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import yaml

from _paths import AGENT_DIR, assert_agent_dir, body_state_path
# F8 (): import the wm_path() RESOLVER (aliased) rather than binding
# the WM_PATH module attribute once at import. wm.py exposes WM_PATH via PEP 562
# __getattr__ (body-WM-aware), but `from wm import WM_PATH` freezes the resolved
# Path at import time; calling wm_path() per use re-resolves through BODY_WM_PATH
# every time. Behavior-preserving here (short-lived CLI, env fixed at launch);
# matches the per-use pattern in tree-encoding-drift-gate.py.
from wm import wm_path as _resolve_wm_path, read_wm, write_wm

# : fail loud at import time if MIND_AGENT unset; replaces the
# opaque `None / "session"` TypeError class the next line would otherwise raise.
assert_agent_dir("compact-restore-slots")

# Body-keyed, agent-wide when unbodied () — the read+delete counterpart
# to precompact-checkpoint.py's write. Bound to a constant rather than resolved
# per-call for the same reason F8 above calls behavior-preserving: short-lived
# CLI, env fixed at launch. Keeping it a constant also preserves the three tests
# that redirect this module attribute directly (guard-1415).
CHECKPOINT_PATH = body_state_path(AGENT_DIR.name, "compact-checkpoint.yaml")


def _is_checkpoint_stale(checkpoint_path, wm_path):
    """True if wm.yaml is fresher than checkpoint — restore would regress.

    g-115-684 fix. Closes the rare-but-significant window where the LLM
    completes an iteration successfully INSIDE the same turn that began
    after PreCompact wrote the checkpoint, so by the time Phase -0.5c
    fires on the next loop entry, wm.yaml carries newer state (e.g.
    counted_goals_this_session has a goal not in the checkpoint's
    loop_state). Running the merge logic would silently drop that goal
    from the counter, double-counting it on the next learning-gate.

    Observed canonical case: zeta session 28 iter 6 (2026-05-13) had
    checkpoint mtime 03:08:38 (mid-iter-5 PreCompact) but wm.yaml mtime
    03:21:55 with counted_goals=[g-115-681, g-115-666]. Checkpoint's
    loop_state had counted=[g-115-681] only (missing g-115-666).
    Resolution at the time: manual delete of stale checkpoint after
    mtime comparison.

    Returns True when wm.yaml strictly newer than checkpoint (the
    regression risk case). Equal mtimes → False (treat as fresh restore).
    Missing files or stat errors → False (fall through to existing
    behavior; fail-open).
    """
    try:
        if not checkpoint_path or not wm_path:
            return False
        if not checkpoint_path.exists() or not wm_path.exists():
            return False
        ck_mtime = checkpoint_path.stat().st_mtime
        wm_mtime = wm_path.stat().st_mtime
        return wm_mtime > ck_mtime
    except OSError:
        return False

# Slots to skip during restoration. Two reasons a slot ends up here:
#   1. Stale by definition (regenerated by the loop) — `archived_context`.
#   2. Latest-wins semantics — restoring an older checkpoint snapshot OVER
#      a newer current value silently reverts cadence stamps and iteration
#      counters. The Map-merge logic at L97-102 unconditionally overwrites
#      current[k] with checkpoint[k] when v is not None, which is wrong for
#      these slots. Documented in  fix (Fix 2), with full incident
#      trace in world/knowledge/tree/system/system-constraints-loop/
#      compact-restore-map-merge-clobber.md ( root cause).
#
# Future dict-shape slot authors: if your slot has timestamp + count fields
# that must reflect the most-recent write across compaction, add it here.
# Heuristic Fix 1 (timestamp-aware merge) is filed as a follow-up Idea goal
# — until it lands, additive SKIP_SLOTS is the safe path.
SKIP_SLOTS = {
    "archived_context",
    "last_felt_sense_checkin",
    "last_fresh_eyes_review",
    "last_fresh_eyes_program_review",
    "last_strategic_scan",
    "loop_state",
    "consolidation_health",
    "portfolio_health_signal",
}


def now_iso():
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


def _delete_checkpoint_safely(path, reason: str) -> bool:
    """One-shot consumption: delete checkpoint at clean success return points.

    g-115-962 fix. Previously the LLM-side Phase -0.5c pseudocode owned the
    delete step ("Step 3: One-shot consumption — Delete checkpoint"), but it
    silently dropped on the stale-skip path — the LLM remembered the delete
    after a successful restore but not after a "restore SKIPPED" early
    return, so the stale file lingered into the next iteration. Single-
    writer principle: the script that owns the checkpoint lifecycle deletes
    it; the LLM no longer carries that responsibility.

    Reasons covered: 'stale-skip', 'empty-checkpoint', 'restored-clean'.
    NOT called from: the 'no checkpoint' early return (nothing to delete)
    OR the wm-uninitialized error exit (preserve for next-iteration retry).

    Returns True on successful (or no-op) deletion, False on OSError —
    callers may ignore the return value (the script never blocks on
    delete-failure: the next iteration's freshness gate will re-handle).

    Takes `path` as arg so the helper is testable without monkey-patching
    module-level CHECKPOINT_PATH (mirrors the testable shape of
    `_is_checkpoint_stale` above).
    """
    try:
        path.unlink(missing_ok=True)
        return True
    except OSError as e:
        print(f"WARN: failed to delete checkpoint ({reason}): {e}", file=sys.stderr)
        return False


def _describe_discarded_checkpoint(checkpoint, wm, skip_slots=None):
    """One-line summary of what a checkpoint held, for the path that DELETES it.

    g-115-4882. The WRITE side counts what it saved — precompact-checkpoint.py
    logs `{eq_count} encoding, {non_null}/{total} slots` — and the DISCARD side
    counted nothing, printing only the mtime delta. So a real encoding_queue
    loss on the stale-skip path was unmeasurable AFTER THE FACT BY CONSTRUCTION:
    the checkpoint is unlinked, and precompact's count only ever went to stderr.
    "No loss reported" read identically to "loss never looked for" (guard-1760,
    rb-245 family).

    This is deliberately the OBSERVABILITY half ONLY. Whether the stale-skip
    should restore encoding_queue at all is a merge-semantics question the
    SKIP_SLOTS comment above already names as open; this function takes no
    position on it and changes no behavior. It exists so that decision finally
    has a denominator.

    Reports two things:
      - the discarded encoding_queue count, distinguishing ABSENT from EMPTY.
        precompact writes that key unconditionally, so absent means a format or
        version mismatch rather than an empty queue, and collapsing the two
        would hide exactly that (guard-1641: a count-like 0 is ambiguous
        between "the producer counted zero" and "the producer never ran").
      - slots the checkpoint held NON-EMPTY while live wm holds them empty or
        null — the ones whose loss the live file does not already cover.

    SKIP_SLOTS are excluded AND said to be excluded: they are never restored by
    design, so naming them would report unrecoverable loss where none exists,
    while dropping them silently would overstate the report's coverage — which
    is the same reporting failure this function was written to end.

    Every unreadable input returns UNKNOWN rather than a reassuring zero, for
    the same reason: the caller is about to delete the only copy.

    Pure — takes the two already-loaded documents, touches no filesystem and no
    module globals. That is the testability contract `_is_checkpoint_stale` and
    `_delete_checkpoint_safely` state for themselves, and it is what lets the
    exec-slice tests in core/scripts/tests reach it without a live agent dir.
    """
    skip = SKIP_SLOTS if skip_slots is None else skip_slots

    if not isinstance(checkpoint, dict):
        return ("checkpoint contents UNKNOWN (not a mapping) — that is not "
                "evidence it was empty")

    if "encoding_queue" in checkpoint:
        eq = checkpoint.get("encoding_queue") or []
        eq_desc = f"{len(eq)} encoding_queue item(s)"
    else:
        eq_desc = ("encoding_queue key ABSENT from the checkpoint (precompact "
                   "writes it unconditionally, so this is a format mismatch, "
                   "NOT an empty queue)")

    all_slots = checkpoint.get("all_slots") or {}
    if not isinstance(all_slots, dict):
        all_slots = {}

    if not isinstance(wm, dict):
        return (f"{eq_desc}; slot comparison UNAVAILABLE (live working memory "
                f"unreadable) — the {len(all_slots)} checkpoint slot(s) are "
                f"unclassified, NOT known-safe")

    live = wm.get("slots") or {}
    if not isinstance(live, dict):
        live = {}

    def _empty(value):
        return value is None or value == [] or value == {} or value == ""

    at_risk = sorted(
        name for name, val in all_slots.items()
        if name not in skip and not _empty(val) and _empty(live.get(name))
    )
    n_skipped = sum(1 for name in all_slots if name in skip)
    if at_risk:
        risk_desc = ", ".join(at_risk)
    elif not all_slots:
        # Same guard-1641 distinction the encoding_queue branch makes above, and
        # it has to be made here too or the function is inconsistent with its own
        # argument: a checkpoint carrying NO slots and one whose slots are all
        # covered by live wm are different facts, and the reassuring phrasing
        # belongs only to the second.
        risk_desc = "n/a — the checkpoint carried NO slots at all"
    else:
        risk_desc = "none (every non-empty slot is also populated in live wm)"
    return (f"{eq_desc}; slots held non-empty here but empty/null in live wm: "
            f"{risk_desc} ({n_skipped} SKIP_SLOTS slot(s) excluded — never "
            f"restored by design, so their loss here is not new)")


def _recover_lost_loop_state():
    """Null-guarded loop_state recovery across compaction ().

    loop_state is in SKIP_SLOTS (the general merge never restores it) AND the
    freshness gate below skips the whole restore when wm.yaml mtime > checkpoint
    mtime. Neither path recovers a loop_state that was NULLED/LOST in the
    compaction window. A null on-disk loop_state is data-loss, never "fresher
    truth" than a valid checkpoint snapshot — and loop-state-bump-counters.py
    would then self-init from goals_completed=0 (g-115-622), silently resetting
    the session count (session_count double-increments, productivity-gate goes
    stale).

    Recovers loop_state from the checkpoint ONLY when the on-disk value is
    null/missing/non-dict, so it can NEVER clobber a valid on-disk loop_state —
    the g-115-593 latest-wins intent that put loop_state in SKIP_SLOTS is fully
    preserved. No-op in the common case (valid on-disk loop_state → no write, so
    the freshness gate's mtime comparison is unaffected). Fail-open: any error →
    no-op (recovery is best-effort, never blocks the general restore).
    """
    try:
        ck = yaml.safe_load(CHECKPOINT_PATH.read_text(encoding="utf-8")) or {}
        ck_ls = (ck.get("all_slots") or {}).get("loop_state")
        if not isinstance(ck_ls, dict):
            return  # checkpoint carries no valid loop_state to recover from
        wm = read_wm()
        if not wm:
            return  # uninitialized wm — main()'s read_wm guard handles this
        slots = wm.setdefault("slots", {})
        disk_ls = slots.get("loop_state")
        if isinstance(disk_ls, dict):
            return  # on-disk loop_state is valid — DO NOT clobber ()
        # on-disk loop_state is null/lost — recover from the checkpoint snapshot
        slots["loop_state"] = ck_ls
        meta = wm.setdefault("slot_meta", {})
        prev = meta.get("loop_state") if isinstance(meta.get("loop_state"), dict) else {}
        meta["loop_state"] = {
            "updated_at": now_iso(),
            "accessed_at": now_iso(),
            "update_count": prev.get("update_count", 0) + 1,
        }
        write_wm(wm)
        gc = ck_ls.get("goals_completed", "?")
        pg = ck_ls.get("productive_goals", "?")
        print(
            f"loop_state RECOVERED from checkpoint (was null on disk; "
            f"goals_completed={gc}, productive_goals={pg}) [g-115-1302]"
        )
    except Exception as e:
        print(f"WARN: loop_state recovery skipped ({e})", file=sys.stderr)


def main():
    if not CHECKPOINT_PATH.exists():
        print("no checkpoint")
        return

    # Capture the freshness decision BEFORE the recovery write below. A
    # recovery write bumps wm.yaml's mtime, which would otherwise make this
    # gate wrongly skip a legitimate general restore — the gate's premise is
    # "an iteration completed after PreCompact", which a recovery write does
    # NOT satisfy. .
    _wm_fresher_than_checkpoint = _is_checkpoint_stale(CHECKPOINT_PATH, _resolve_wm_path())

    # : recover loop_state if it was nulled/lost in the compaction
    # window. MUST run before the general merge — loop_state is in SKIP_SLOTS
    # (never restored) and the freshness gate below skips the whole restore,
    # so neither would recover it. Null-guarded: no-op (no write) when on-disk
    # loop_state is a valid dict, so existing behavior is unchanged then.
    _recover_lost_loop_state()

    # Freshness gate (): when wm.yaml mtime exceeds checkpoint mtime,
    # the in-process iteration completed after PreCompact, so wm.yaml carries
    # newer state. Running the merge logic here would silently regress
    # counters and slot values. SKIP the restore + delete the stale
    # checkpoint (: was LLM-owned Phase -0.5c Step 3; moved here so
    # the stale-skip path can no longer leak).
    # MEASURED box identity, surfaced BEFORE any restore branch ().
    # Placed above the stale-skip below on purpose: a stale-skip resume still
    # produces a summary, so it needs the measured value just as much as a
    # clean restore does -- gating this on a successful restore would leave the
    # exact path that recovers least with no ground truth at all.
    # The point is ORDERING: this line lands in the resume context ahead of the
    # summary prose, so an inherited hostname has something to contradict it.
    # Fail-open -- a missing stamp (any checkpoint written before this shipped)
    # prints nothing and changes no behaviour.
    # NOTE: `checkpoint` is NOT bound in main() -- it is a PARAMETER of
    # _describe_discarded_checkpoint(). Referencing it here raised NameError,
    # which this very except swallowed, so the surface was silently dead from
    # the moment it shipped (guard-3803: a fail-open handler also covers bugs
    # in the code it wraps; rb-9581: line order is not scope). Parse locally.
    try:
        _ck_doc = yaml.safe_load(CHECKPOINT_PATH.read_text(encoding="utf-8")) or {}
        _box = _ck_doc.get("box_identity") or {}
        if _box.get("machine_id"):
            print(
                "box identity (MEASURED at checkpoint write, not from summary "
                f"prose): machine_id={_box.get('machine_id')} "
                f"uname={_box.get('platform_uname', 'unknown')}"
            )
    except Exception:
        pass

    if _wm_fresher_than_checkpoint:
        ck_mtime = CHECKPOINT_PATH.stat().st_mtime
        wm_mtime = _resolve_wm_path().stat().st_mtime
        delta = wm_mtime - ck_mtime
        print(
            f"checkpoint stale (wm.yaml is {delta:.0f}s fresher than checkpoint) — "
            f"restore SKIPPED to prevent loop_state regression (g-115-684)"
        )
        # : say WHAT is being discarded, BEFORE unlinking the only
        # copy. Additive — the stale-skip still skips and still deletes.
        #
        # Fail-open and deliberately AFTER the SKIPPED line: this path never
        # parsed the checkpoint before, so a malformed one still got deleted
        # cleanly, and that must stay true. A diagnostic that can break the
        # operation it describes is worse than no diagnostic (guard-1562).
        #
        # Both branches print to STDOUT, matching the SKIPPED line above rather
        # than the WARN in _delete_checkpoint_safely: an unreadable checkpoint
        # is exactly when this report matters most, and stderr is the channel a
        # captured-output caller drops (guard-1680).
        try:
            _discarded = yaml.safe_load(CHECKPOINT_PATH.read_text(encoding="utf-8"))
            _live_wm = read_wm()
        except Exception as exc:  # noqa: BLE001 — any read/parse fault, never fatal
            print(
                f"  discarding: could not read checkpoint or wm for the discard "
                f"report ({exc.__class__.__name__}: {exc}) — contents UNKNOWN, "
                f"which is NOT the same as empty"
            )
        else:
            print("  discarding: " + _describe_discarded_checkpoint(_discarded, _live_wm))
        _delete_checkpoint_safely(CHECKPOINT_PATH, "stale-skip")
        return

    checkpoint = yaml.safe_load(CHECKPOINT_PATH.read_text(encoding="utf-8")) or {}
    all_slots = checkpoint.get("all_slots") or {}
    saved_meta = checkpoint.get("slot_meta") or {}

    if not all_slots:
        print("no slots in checkpoint")
        _delete_checkpoint_safely(CHECKPOINT_PATH, "empty-checkpoint")
        return

    wm = read_wm()
    if not wm:
        # Preserve checkpoint for next-iteration retry — wm-init may recover.
        print("ERROR: Working memory not initialized", file=sys.stderr)
        sys.exit(1)

    wm_slots = wm.setdefault("slots", {})
    wm_meta = wm.setdefault("slot_meta", {})

    restored = []
    skipped = []
    merged = []

    for slot_name, saved_value in all_slots.items():
        # Skip list
        if slot_name in SKIP_SLOTS:
            skipped.append(slot_name)
            continue

        # Skip null/empty values from checkpoint
        if saved_value is None:
            continue
        if isinstance(saved_value, list) and not saved_value:
            continue
        if isinstance(saved_value, dict) and not any(v is not None for v in saved_value.values()):
            continue

        current = wm_slots.get(slot_name)

        # Merge logic
        if isinstance(saved_value, list) and isinstance(current, list) and current:
            # Array merge: extend with checkpoint items not already present
            existing_set = {
                json.dumps(item, sort_keys=True, default=str) if isinstance(item, dict) else str(item)
                for item in current
            }
            added = 0
            for item in saved_value:
                key = json.dumps(item, sort_keys=True, default=str) if isinstance(item, dict) else str(item)
                if key not in existing_set:
                    current.append(item)
                    existing_set.add(key)
                    added += 1
            if added:
                merged.append(f"{slot_name}(+{added})")
        elif isinstance(saved_value, dict) and isinstance(current, dict) and current:
            # Map merge with timestamp-aware preference (, Fix 1 of ).
            # Sibling to the SKIP_SLOTS list above (Fix 2, ) — that list
            # names the slots known today to need latest-wins semantics. THIS
            # branch protects FUTURE dict-shape slots whose authors forget to add
            # to SKIP_SLOTS: when both dicts carry an epoch-like field, keep the
            # newer one; when timestamps are missing or ambiguous, fall through
            # to the original checkpoint-wins semantics for backward compat.
            cur_ts = current.get("timestamp") or current.get("updated_at") or current.get("time")
            chk_ts = saved_value.get("timestamp") or saved_value.get("updated_at") or saved_value.get("time")
            if cur_ts and chk_ts and cur_ts >= chk_ts:
                # Current is newer than checkpoint — preserve it. Fill nulls
                # from checkpoint (don't overwrite anything current already has).
                for k, v in saved_value.items():
                    if v is not None and current.get(k) is None:
                        current[k] = v
            else:
                # Current is older OR timestamps missing OR undeterminable.
                # Fall back to original checkpoint-wins for backward compat —
                # SKIP_SLOTS still names the slots where even this is wrong.
                for k, v in saved_value.items():
                    if v is not None:
                        current[k] = v
            merged.append(slot_name)
        else:
            # Scalar or replacing empty: direct overwrite
            wm_slots[slot_name] = saved_value
            restored.append(slot_name)

        # Restore slot_meta timestamps
        if slot_name in saved_meta:
            sm = saved_meta[slot_name]
            wm_meta[slot_name] = {
                "updated_at": sm.get("updated_at") or now_iso(),
                "accessed_at": sm.get("accessed_at") or now_iso(),
                "update_count": sm.get("update_count", 0),
            }

    # Restore top-level WM keys from checkpoint
    top_restored = []
    for key in ["goals_completed_this_session", "aspiration_touched_last", "last_goal_category"]:
        val = checkpoint.get(key)
        if val is not None and val != "" and val != []:
            wm[key] = val
            top_restored.append(key)

    write_wm(wm)

    # Output summary for the LLM
    parts = []
    if restored:
        parts.append(f"restored: {', '.join(restored)}")
    if merged:
        parts.append(f"merged: {', '.join(merged)}")
    if skipped:
        parts.append(f"skipped: {', '.join(skipped)}")
    if top_restored:
        parts.append(f"top-level: {', '.join(top_restored)}")

    total = len(restored) + len(merged)
    summary = f"{total} slots recovered"
    if parts:
        summary += f" ({'; '.join(parts)})"
    print(summary)

    _delete_checkpoint_safely(CHECKPOINT_PATH, "restored-clean")


if __name__ == "__main__":
    main()
